# -*- coding: utf-8 -*-
"""Provider management — models, registry + persistent store."""

from .models import (
    ActiveModelsInfo,
    CustomProviderData,
    ModelInfo,
    ModelSlotConfig,
    ProviderDefinition,
    ProviderInfo,
    ProviderSettings,
    ProvidersData,
    ResolvedModelConfig,
)
from .registry import (
    PROVIDERS,
    get_chat_model_class,
    get_provider,
    get_provider_chat_model,
    is_builtin,
    list_providers,
    sync_local_models,
)
from .store import (
    add_fallback_llm,
    add_model,
    create_custom_provider,
    delete_custom_provider,
    get_active_llm_config,
    get_fallback_llm_configs,
    load_providers_json,
    mask_api_key,
    remove_fallback_llm,
    remove_model,
    save_providers_json,
    set_active_llm,
    set_fallback_llms,
    update_provider_settings,
)

__all__ = [
    "ActiveModelsInfo",
    "CustomProviderData",
    "ModelInfo",
    "ModelSlotConfig",
    "ProviderDefinition",
    "ProviderInfo",
    "ProviderSettings",
    "ProvidersData",
    "ResolvedModelConfig",
    "PROVIDERS",
    "get_chat_model_class",
    "get_provider",
    "get_provider_chat_model",
    "is_builtin",
    "list_providers",
    "sync_local_models",
    "add_fallback_llm",
    "add_model",
    "create_custom_provider",
    "delete_custom_provider",
    "get_active_llm_config",
    "get_fallback_llm_configs",
    "load_providers_json",
    "mask_api_key",
    "remove_fallback_llm",
    "remove_model",
    "save_providers_json",
    "set_active_llm",
    "set_fallback_llms",
    "update_provider_settings",
]
